services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: poetry run fastapi run --port 8000 /car_wash/main.py
    volumes:
      - ./car_wash:/car_wash
    env_file:
      - .env
    environment:
      IN_DOCKER: True
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    container_name: car_wash_db
    ports:
      - 5434:5432

  minio:
    image: minio/minio
    container_name: minio_server
    restart: always
    volumes:
      - minio_volume:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
    command: server --address ":9000" --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  postgres_volume:
  minio_volume:
