services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    container_name: car_wash_db
    ports:
      - 5434:5432

volumes:
  postgres_volume:
