"""empty message

Revision ID: 61816b8072f2
Revises: 5798288049bd
Create Date: 2024-09-04 20:57:44.335268

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '61816b8072f2'
down_revision: Union[str, None] = '5798288049bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user__refresh_token_user_id', table_name='user__refresh_token')
    op.create_index(op.f('ix_user__refresh_token_user_id'), 'user__refresh_token', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user__refresh_token_user_id'), table_name='user__refresh_token')
    op.create_index('ix_user__refresh_token_user_id', 'user__refresh_token', ['user_id'], unique=False)
    # ### end Alembic commands ###
