"""empty message

Revision ID: 4f7dd4f24c07
Revises: 225d04568ac3
Create Date: 2024-09-03 23:22:16.254765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f7dd4f24c07'
down_revision: Union[str, None] = '225d04568ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_wash__booking',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('car_wash_id', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('is_exception', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['car_wash_id'], ['car_wash.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_wash__schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_wash_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_wash_id'], ['car_wash.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('booking')
    op.drop_table('schedule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('car_wash_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['car_wash_id'], ['car_wash.id'], name='schedule_car_wash_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='schedule_pkey')
    )
    op.create_table('booking',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('car_wash_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_exception', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['car_wash_id'], ['car_wash.id'], name='booking_car_wash_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='booking_pkey')
    )
    op.drop_table('car_wash__schedule')
    op.drop_table('car_wash__booking')
    # ### end Alembic commands ###
