"""empty message

Revision ID: 5798288049bd
Revises: 9ca350627a46
Create Date: 2024-09-03 23:59:26.306036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5798288049bd'
down_revision: Union[str, None] = '9ca350627a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_wash__booking', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_wash__booking', 'created_at')
    # ### end Alembic commands ###
