"""empty message

Revision ID: 9ca350627a46
Revises: 4f7dd4f24c07
Create Date: 2024-09-03 23:49:41.493968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca350627a46'
down_revision: Union[str, None] = '4f7dd4f24c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_wash__booking', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('car_wash__booking', 'car_wash_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'car_wash__booking', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_wash__booking', type_='foreignkey')
    op.alter_column('car_wash__booking', 'car_wash_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('car_wash__booking', 'user_id')
    # ### end Alembic commands ###
