"""empty message

Revision ID: d445484e6aaa
Revises: 516330b0185f
Create Date: 2025-01-08 17:18:30.692359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd445484e6aaa'
down_revision: Union[str, None] = '516330b0185f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_wash__addition', sa.Column('name', sa.String(), nullable=False))
    op.add_column('car_wash__addition', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('car_wash__addition', 'additional_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_wash__addition', sa.Column('additional_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('car_wash__addition', 'price')
    op.drop_column('car_wash__addition', 'name')
    # ### end Alembic commands ###
