"""empty message

Revision ID: 0e8ad1299d4c
Revises: d445484e6aaa
Create Date: 2025-01-08 17:19:53.159384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8ad1299d4c'
down_revision: Union[str, None] = 'd445484e6aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_car_wash_addition___car_wash_id__name', 'car_wash__addition', ['car_wash_id', 'name'])
    op.create_unique_constraint(None, 'car_wash__addition', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_wash__addition', type_='unique')
    op.drop_constraint('uix_car_wash_addition___car_wash_id__name', 'car_wash__addition', type_='unique')
    # ### end Alembic commands ###
