"""empty message

Revision ID: b052f441a561
Revises: 0e8ad1299d4c
Create Date: 2025-01-08 17:20:07.555348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b052f441a561'
down_revision: Union[str, None] = '0e8ad1299d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_wash__addition_name_key', 'car_wash__addition', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('car_wash__addition_name_key', 'car_wash__addition', ['name'])
    # ### end Alembic commands ###
