"""empty message

Revision ID: 34a6b2835aa8
Revises: a90e1999ff06
Create Date: 2025-01-06 18:53:03.321724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a6b2835aa8'
down_revision: Union[str, None] = 'a90e1999ff06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_wash__booking', sa.Column('user_car_id', sa.Integer(), nullable=False))
    op.drop_constraint('car_wash__booking_user_id_fkey', 'car_wash__booking', type_='foreignkey')
    op.create_foreign_key(None, 'car_wash__booking', 'user_car', ['user_car_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('car_wash__booking', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_wash__booking', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'car_wash__booking', type_='foreignkey')
    op.create_foreign_key('car_wash__booking_user_id_fkey', 'car_wash__booking', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('car_wash__booking', 'user_car_id')
    # ### end Alembic commands ###
