"""empty message

Revision ID: a90e1999ff06
Revises: d1247d882db3
Create Date: 2025-01-06 18:10:13.480361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90e1999ff06'
down_revision: Union[str, None] = 'd1247d882db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_wash__booking', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('car_wash__booking', sa.Column('is_accepted', sa.Boolean(), nullable=False))
    op.add_column('user_car', sa.Column('license_plate', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_car', 'license_plate')
    op.drop_column('car_wash__booking', 'is_accepted')
    op.drop_column('car_wash__booking', 'is_completed')
    # ### end Alembic commands ###
